server {
    listen 80 default_server;
    
    # GlennGO marketing
    if ($host = marketing.glenngo.com) {
        root /usr/share/nginx/html/glenngo;
    }
    
    # REPLai Pilot marketing
    if ($host = marketing.replaipilot.com) {
        root /usr/share/nginx/html/replai-pilot;
    }
    
    # Default fallback
    root /usr/share/nginx/html/glenngo;
    
    index index.html;
    
    location / {
        try_files $uri $uri/ =404;
    }
}
